name: cup_and_soup
description: A new Flutter project.

version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rxdart: ^0.21.0
  firebase_auth: ^0.8.4+2
  google_sign_in: ^4.0.1+3
  cloud_firestore: ^0.9.13
  firebase_database: ^2.0.2
  firebase_storage: ^2.1.0+1
  cloud_functions: ^0.1.2+1
  flutter_launcher_icons: "^0.7.0"
  shared_preferences: ^0.5.1+2
  flare_flutter: ^1.3.8
  image_picker: ^0.5.3+1
  flutter_barcode_scanner: ^0.0.8
<<<<<<< HEAD
  flutter_tags: "^0.1.9"

=======
  barcode_flutter: ^1.0.0
>>>>>>> e7c0294135a60a2fa1f617682b201efa7a2cd89f
  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/logo.png
   - assets/images/room10.png
   - assets/images/loading.png

   - assets/flare/phoneVerify.flr

  fonts:
    - family: BrandFont
      fonts:
        - asset: assets/fonts/BillionaireMediumGrunge.ttf
    - family: PrimaryFont
      fonts:
        - asset: assets/fonts/UbuntuCondensed-Regular.ttf
    - family: SeconderyFont
      fonts:
        - asset: assets/fonts/coffee+teademo-Regular.ttf
