name: cup_and_soup
description: The official restaurant of the kingdom.

author: Zvi Karp <zvi@zektec.com>
version: 0.2.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
    
  cupertino_icons: ^0.1.2
  intl: ^0.15.8
  rxdart: ^0.21.0
  firebase_auth: ^0.8.4+2
  google_sign_in: ^4.0.1+3
  cloud_firestore: ^0.9.13
  firebase_database: ^2.0.2
  firebase_storage: ^2.1.0+1
  cloud_functions: ^0.1.2+1
  flutter_launcher_icons: "^0.7.0"
  shared_preferences: ^0.5.1+2
  flare_flutter: ^1.5.1
  image_picker: ^0.5.3+1
  flutter_barcode_scanner: ^0.0.8
  barcode_flutter: ^1.0.0
  flutter_tags: ^0.3.0
  flushbar: 1.5.3
  url_launcher: ^5.0.2
  firebase_messaging: ^4.0.0+4
  firebase_crashlytics: ^0.0.4+3
  sqflite: ^1.1.5
  path_provider: ^1.0.0
  http: ^0.12.0+2
  transparent_image: ^1.0.0
  flutter_svg: 0.12.4+1
  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/logo.png
   - assets/images/room10.png
   - assets/images/loading.png
   - assets/images/header.png
   - assets/images/navBar.png
   - assets/images/center.png
   - assets/images/divider.png
   - assets/images/dialogBackground.png
   - assets/images/add.png
   - assets/images/icon.png

   - assets/images/divider.svg
   - assets/images/dialogBackground.svg
   - assets/images/center.svg
   - assets/images/navBar.svg
   
   - assets/images/navigation.png

   - assets/flare/basket.flr
   - assets/flare/barcode.flr
   - assets/flare/user.flr
   - assets/flare/lock.flr
   - assets/flare/star.flr

  fonts:
    - family: BrandFont
      fonts:
        - asset: assets/fonts/BillionaireMediumGrunge.ttf
    - family: PrimaryFont
      fonts:
        - asset: assets/fonts/UbuntuCondensed-Regular.ttf
    - family: SeconderyFont
      fonts:
        - asset: assets/fonts/coffee+teademo-Regular.ttf
    - family: HeBrandFont
      fonts:
        - asset: assets/fonts/TsMatka-Regular.ttf
